# Generated by Django 3.1.6 on 2021-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('interviewer_email', models.EmailField(default='', max_length=254)),
                ('interviewer_name', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(default='', max_length=254)),
                ('candidate_name', models.CharField(max_length=100)),
            ],
        ),
    ]
